stages:
  - prepare
  - validate
  - stage
  - production


prepare_dependencies:
  stage: prepare
  script:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r scripts/requirements.txt
  - mkdir .ctf
  - |
    cat <<EOF > .ctf/config
    [challenges]

    [config]
    url = https://ctfd.uralctf.org
    access_token = $CTFD_API_KEY
    EOF
  artifacts:
    paths:
      - "venv/**"
      - ".ctf/**"

validate_task_structure:
  stage: validate
  needs:
    - prepare_dependencies
  script:
    - source venv/bin/activate
    - python3 scripts/validate_structure.py
  rules:
    - changes:
      - tasks/**/*

validate_tasks:
  stage: validate
  needs: 
    - prepare_dependencies
    - validate_task_structure
  script:
    - source venv/bin/activate
    - python3 scripts/validate_tasks.py
  rules:
    - changes:
      - tasks/**/*

validate_ports:
  stage: validate
  needs: 
    - prepare_dependencies
    - validate_task_structure
  script:
    - source venv/bin/activate
    - python3 scripts/validate_ports.py
  rules:
    - changes:
      - tasks/**/*

deploy_stage:
  stage: stage
  tags: [staged]
  script:
    - chmod +x scripts/deploy_tasks.sh
    - scripts/deploy_tasks.sh
  rules:
    - changes:
      - tasks/**/*

deploy_tasks:
  stage: production
  tags: [tasks-deploy]
  script:
    - chmod +x scripts/deploy_tasks.sh
    - scripts/deploy_tasks.sh
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"

deploy_tasks_to_ctfd:
  stage: production
  dependencies:
    - prepare_dependencies
  script:
    - source venv/bin/activate
    - python3 scripts/fetch_tasks.py
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
