stages:
  - validate
  - stage
  - production

.dependencies_installation: &dependencies
  - pip install -r scripts/requirements.txt
  - mkdir .ctf
  - |
    cat <<EOF > .ctf/config
    [challenges]

    [config]
    url = https://ctfd.uralctf.org
    access_token = $CTFD_API_KEY
    EOF

validate_task_structure:
  stage: validate
  script:
    - *dependencies
    - python3 scripts/validate_structure.py
  rules:
    - changes:
      - tasks/**/*

validate_tasks:
  stage: validate
  needs: [validate_task_structure]
  script:
    - *dependencies
    - python3 scripts/validate_tasks.py
  rules:
    - changes:
      - tasks/**/*

validate_ports:
  stage: validate
  needs: [validate_task_structure]
  script:
    - *dependencies
    - python3 scripts/validate_ports.py
  rules:
    - changes:
      - tasks/**/*

deploy_stage:
  stage: stage
  tags: [staged]
  script:
    - chmod +x scripts/deploy_tasks.sh
    - scripts/deploy_tasks.sh
  rules:
    - changes:
      - tasks/**/*

deploy_tasks:
  stage: production
  tags: [tasks-deploy]
  script:
    - chmod +x scripts/deploy_tasks.sh
    - scripts/deploy_tasks.sh
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"

deploy_tasks_to_ctfd:
  stage: production
  script:
    - *dependencies
    - python3 scripts/fetch_tasks.py
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
