stages:
  - validate
  - deploy

validate_task_structure:
  stage: validate
  tags: [tasks-deploy]
  script:
    - python3 scripts/validate_structure.py
  only:
    changes:
      - tasks/*

validate_tasks:
  stage: validate
  tags: [tasks-deploy]
  needs: [validate_task_structure]
  script:
    - python3 scripts/validate_tasks.py
  only:
    changes:
      - tasks/*

validate_ports:
  stage: validate
  tags: [tasks-deploy]
  needs: [validate_task_structure]
  script:
    - python3 scripts/validate_ports.py
  only:
    changes:
      - tasks/*

deploy_tasks:
  stage: deploy
  tags: [k8s]
  script:
    - pip3 install ctfcli
    - mkdir .ctf
    - |
      cat <<EOF > .ctf/config
      [challenges]

      [config]
      url = https://ctfd.uralctf.org
      access_token = $CTFD_API_KEY
      EOF
    - chmod +x scripts/deploy_tasks.sh
    - scripts/deploy_tasks.sh
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
