name: "Pyromancy"
author: "@w1p30ut"
category: "web"
description: |
  Какие-то очередные "стартаперы" предложили нам внедрить их решение. Надо бы проверить его на безопасность...
# attribution: "Автор [@w1p30ut](https://t.me/w1p30ut)"
value: 1000
type: dynamic

# Reference - https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
extra:
    initial: 1000
    decay: 20
    minimum: 60

connection_info: "http://5.1.53.43:5645"
flags:
  - UralCTF{3mbr4c3_7h3_fl4m3}
tags:
  - web
  - easy
files: 
hints: 
state: visible
version: "0.1"
