services:
  test_task:
    build: .
    ports:
      - "5099:5000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.5'
          memory: 64M
