# Имя, которое отразится на платформе CTFd
name: "rsa-3"
# Ваш Telegram никнейм (не отображается на платформе)
author: "@nikoil"
# Категория - название папки, в которой лежит таск
category: "crypto"
# Категория будет отображаться на платформе в описании таска. Поддерживается md формат 
description: |
  Я опять написал свой RSA 
  Его точно точно не взломать 
# Ссылка на ваш ТГ аккаунт, чтобы с вами могли оперативно связаться по задаче
attribution: ""
value: 1000
type: dynamic

# Reference - https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
extra:
    initial: 1000
    decay: 40
    minimum: 50

flags:
  - UralCTF{92c4770804563ee0b3a3b935f7bc7226a14710c84e9d8f27e8daedb7a8ad73c66d4e7029a5dfcb923ccac697a45fe65882ea9231476f7d8d0a8afd96a8e9e1d3}

tags:
  - crypto
  - medium
files: 
  - public/*
state: visible
version: "0.1"
